FROM python:3.12

ARG FACEFUSION_VERSION=3.1.2
ENV FACEFUSION_VERSION=${FACEFUSION_VERSION}
ENV GRADIO_SERVER_NAME=0.0.0.0
ENV PIP_BREAK_SYSTEM_PACKAGES=1

WORKDIR /facefusion

RUN apt-get update && apt-get install -y curl ffmpeg git

# Re-declare ARG in this layer to ensure it's available to RUN
ARG FACEFUSION_VERSION
RUN git clone https://github.com/fidelweiss/facefusion.git --branch ${FACEFUSION_VERSION} --single-branch .

RUN python install.py --onnxruntime default --skip-conda
